In [1]:
import pandas as pd

In [2]:
#reading train data
train = pd.read_csv('train.csv', encoding="cp1252")
print(train.shape)
train.sample(5)

(27481, 10)

,textID,text,selected_text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
27037,481e43e353,can`t sleep so i`m watching some more Gilmore ...,can`t sleep so,neutral,noon,21-30,Romania,19237691,230170.0,84
4758,36c471e4a7,Doing uni work all weekend. Fun times,Fun times,positive,morning,0-20,Kuwait,4270571,17820.0,240
15712,a9e033d39c,I also found out that it`s also my last youth ...,I also found out that it`s also my last youth ...,neutral,noon,60-70,Somalia,15893222,627340.0,25
8325,ba14fc298b,"Awake again , I give up , I`m going to ready f...","Awake again , I give up , I`m going to ready f...",neutral,morning,46-60,Solomon Islands,686884,28000.0,25
8137,df464ec6cf,The sun is attempting to increase her efforts....,Alas,negative,noon,21-30,Sudan,43849260,1765048.0,25

In [4]:
#reading test data
import pandas as pd
test = pd.read_csv('test.csv', encoding='latin-1')
print(test.shape)
test.head()

(4815, 9)

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,f87dea47db,Last session of the day http://twitpic.com/67ezh,neutral,morning,0-20,Afghanistan,38928346.0,652860.0,60.0
1,96d74cb729,Shanghai is also really exciting (precisely -...,positive,noon,21-30,Albania,2877797.0,27400.0,105.0
2,eee518ae67,"Recession hit Veronique Branquinho, she has to...",negative,night,31-45,Algeria,43851044.0,2381740.0,18.0
3,01082688c6,happy bday!,positive,morning,46-60,Andorra,77265.0,470.0,164.0
4,33987a8ee5,http://twitpic.com/4w75p - I like it!!,positive,noon,60-70,Angola,32866272.0,1246700.0,26.0